- name: Call GET Route with Retry
  run: |
    MAX_RETRIES=5
    RETRY_DELAY=60
    ATTEMPT=1

    while [ $ATTEMPT -le $MAX_RETRIES ]; do
      echo "Attempt $ATTEMPT: Pinging the API..."
      STATUS=$(curl --max-time 60 -s -o /dev/null -w "%{http_code}" https://mimir-c69y.onrender.com/)
      echo "Response Code: $STATUS"

      if [ "$STATUS" -eq 200 ]; then
        echo "Success: API is healthy."
        exit 0
      fi

      if [ $ATTEMPT -lt $MAX_RETRIES ]; then
        echo "Retrying in $RETRY_DELAY seconds..."
        sleep $RETRY_DELAY
      fi

      ATTEMPT=$((ATTEMPT + 1))
    done

    echo "Failed to get a 200 OK after $MAX_RETRIES attempts."
    # Mark job as success to suppress email
    exit 0
